// SeaRM Widget Data Sources - Registry of all queryable tables
// Each source defines which columns are publicly exposable and their types.
// Adding a new source = adding one entry here. Everything else adapts automatically.

import type { DataSourceDefinition } from "./types"

export const DATA_SOURCES: DataSourceDefinition[] = [
  {
    key: "voyages",
    label: "Voyages",
    table: "voyages",
    description: "Active and past voyages with routes, dates, and mission info",
    category: "Operations",
    defaultSort: "departure_date",
    defaultSortDir: "desc",
    columns: [
      { key: "id", label: "ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "voyage_name", label: "Voyage Name", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "ship_id", label: "Ship ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "departure_port", label: "Departure Port", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "destination_port", label: "Destination Port", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "departure_date", label: "Departure Date", type: "date", sortable: true, filterable: true, defaultVisible: true },
      { key: "return_date", label: "Return Date", type: "date", sortable: true, filterable: true, defaultVisible: true },
      { key: "status", label: "Status", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "mission_type", label: "Mission Type", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "mission_objectives", label: "Mission Objectives", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "description", label: "Description", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "notes", label: "Notes", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "created_at", label: "Created", type: "date", sortable: true, filterable: true, defaultVisible: false },
      { key: "updated_at", label: "Updated", type: "date", sortable: true, filterable: false, defaultVisible: false },
    ],
  },
  {
    key: "ships",
    label: "Ships / Vessels",
    table: "ships",
    description: "Fleet information including vessel specs and status",
    category: "Operations",
    defaultSort: "name",
    columns: [
      { key: "id", label: "ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "name", label: "Ship Name", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "type", label: "Vessel Type", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "flag", label: "Flag State", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "imo_number", label: "IMO Number", type: "text", sortable: false, filterable: true, defaultVisible: false },
      { key: "call_sign", label: "Call Sign", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "mmsi", label: "MMSI", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "length_m", label: "Length (m)", type: "number", sortable: true, filterable: true, defaultVisible: true },
      { key: "beam_m", label: "Beam (m)", type: "number", sortable: true, filterable: false, defaultVisible: false },
      { key: "draft_m", label: "Draft (m)", type: "number", sortable: true, filterable: false, defaultVisible: false },
      { key: "gross_tonnage", label: "Gross Tonnage", type: "number", sortable: true, filterable: true, defaultVisible: true },
      { key: "crew_capacity", label: "Crew Capacity", type: "number", sortable: true, filterable: true, defaultVisible: true },
      { key: "year_built", label: "Year Built", type: "number", sortable: true, filterable: true, defaultVisible: true },
      { key: "hull_material", label: "Hull Material", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "engine_type", label: "Engine Type", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "max_speed_knots", label: "Max Speed (kts)", type: "number", sortable: true, filterable: true, defaultVisible: false },
      { key: "home_port", label: "Home Port", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "status", label: "Status", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "notes", label: "Notes", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "created_at", label: "Created", type: "date", sortable: true, filterable: false, defaultVisible: false },
      { key: "updated_at", label: "Updated", type: "date", sortable: true, filterable: false, defaultVisible: false },
    ],
  },
  {
    key: "crew_applications",
    label: "Crew Applications",
    table: "crew_applications",
    description: "Submitted crew membership applications and their status",
    category: "Crew",
    defaultSort: "created_at",
    defaultSortDir: "desc",
    columns: [
      { key: "id", label: "ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "first_name", label: "First Name", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "last_name", label: "Last Name", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "email", label: "Email", type: "email", sortable: true, filterable: true, defaultVisible: true },
      { key: "phone", label: "Phone", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "status", label: "Status", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "rating", label: "Rating", type: "number", sortable: true, filterable: true, defaultVisible: true },
      { key: "gender", label: "Gender", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "country", label: "Country", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "city", label: "City", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "date_of_birth", label: "Date of Birth", type: "date", sortable: true, filterable: false, defaultVisible: false },
      { key: "current_occupation", label: "Occupation", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "department_preference", label: "Dept. Preference", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "maritime_qualifications", label: "Qualifications", type: "text", sortable: false, filterable: true, defaultVisible: false },
      { key: "languages", label: "Languages", type: "text", sortable: false, filterable: true, defaultVisible: false },
      { key: "availability_start_date", label: "Available From", type: "date", sortable: true, filterable: true, defaultVisible: false },
      { key: "availability_end_date", label: "Available Until", type: "date", sortable: true, filterable: true, defaultVisible: false },
      { key: "duration", label: "Duration", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "pronouns", label: "Pronouns", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "created_at", label: "Applied", type: "date", sortable: true, filterable: true, defaultVisible: true },
      { key: "updated_at", label: "Updated", type: "date", sortable: true, filterable: false, defaultVisible: false },
    ],
  },
  {
    key: "crew_assignments",
    label: "Crew Assignments",
    table: "crew_assignments",
    description: "Crew member voyage assignments and roles",
    category: "Crew",
    defaultSort: "created_at",
    defaultSortDir: "desc",
    columns: [
      { key: "id", label: "ID", type: "text", sortable: true, filterable: false, defaultVisible: false },
      { key: "crew_id", label: "Crew ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "voyage_id", label: "Voyage ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "position_id", label: "Position ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "role", label: "Role", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "department", label: "Department", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "status", label: "Status", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "expected_join_date", label: "Expected Join", type: "date", sortable: true, filterable: true, defaultVisible: true },
      { key: "actual_join_date", label: "Actual Join", type: "date", sortable: true, filterable: true, defaultVisible: false },
      { key: "expected_departure_date", label: "Expected Departure", type: "date", sortable: true, filterable: true, defaultVisible: true },
      { key: "actual_departure_date", label: "Actual Departure", type: "date", sortable: true, filterable: true, defaultVisible: false },
      { key: "sign_on_date", label: "Sign On", type: "date", sortable: true, filterable: true, defaultVisible: false },
      { key: "sign_off_date", label: "Sign Off", type: "date", sortable: true, filterable: true, defaultVisible: false },
      { key: "days_at_sea", label: "Days at Sea", type: "number", sortable: true, filterable: true, defaultVisible: true },
      { key: "crew_review_rating", label: "Review Rating", type: "number", sortable: true, filterable: true, defaultVisible: false },
      { key: "notes", label: "Notes", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "created_at", label: "Created", type: "date", sortable: true, filterable: true, defaultVisible: false },
      { key: "updated_at", label: "Updated", type: "date", sortable: true, filterable: false, defaultVisible: false },
    ],
  },
  {
    key: "crew_sea_time",
    label: "Sea Time Records",
    table: "crew_sea_time",
    description: "Logged sea time entries for crew members",
    category: "Crew",
    defaultSort: "created_at",
    defaultSortDir: "desc",
    columns: [
      { key: "id", label: "ID", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "crew_id", label: "Crew ID", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "ship_id", label: "Ship ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "voyage_id", label: "Voyage ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "role", label: "Role", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "embarked_at", label: "Embarked", type: "date", sortable: true, filterable: true, defaultVisible: true },
      { key: "disembarked_at", label: "Disembarked", type: "date", sortable: true, filterable: true, defaultVisible: true },
      { key: "days", label: "Days", type: "number", sortable: true, filterable: true, defaultVisible: true },
      { key: "notes", label: "Notes", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "created_at", label: "Created", type: "date", sortable: true, filterable: false, defaultVisible: false },
    ],
  },
  {
    key: "tasks",
    label: "Tasks",
    table: "tasks",
    description: "Task management records with assignments and status",
    category: "Operations",
    defaultSort: "created_at",
    defaultSortDir: "desc",
    columns: [
      { key: "id", label: "ID", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "title", label: "Title", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "description", label: "Description", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "task_type", label: "Type", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "status", label: "Status", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "priority", label: "Priority", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "crew_id", label: "Crew ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "voyage_id", label: "Voyage ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "ship_id", label: "Ship ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "assigned_to", label: "Assigned To", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "due_date", label: "Due Date", type: "date", sortable: true, filterable: true, defaultVisible: true },
      { key: "completed_at", label: "Completed", type: "date", sortable: true, filterable: true, defaultVisible: false },
      { key: "created_at", label: "Created", type: "date", sortable: true, filterable: true, defaultVisible: false },
      { key: "updated_at", label: "Updated", type: "date", sortable: true, filterable: false, defaultVisible: false },
    ],
  },
  {
    key: "incidents",
    label: "Incidents & Reports",
    table: "incidents",
    description: "Safety incidents, near-misses, and event reports",
    category: "Safety",
    defaultSort: "occurred_at",
    defaultSortDir: "desc",
    columns: [
      { key: "id", label: "ID", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "title", label: "Title", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "description", label: "Description", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "severity", label: "Severity", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "category", label: "Category", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "status", label: "Status", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "voyage_id", label: "Voyage ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "ship_id", label: "Ship ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "location", label: "Location", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "occurred_at", label: "Occurred At", type: "date", sortable: true, filterable: true, defaultVisible: true },
      { key: "reported_by", label: "Reported By", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "corrective_actions", label: "Corrective Actions", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "follow_up", label: "Follow Up", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "created_at", label: "Created", type: "date", sortable: true, filterable: false, defaultVisible: false },
      { key: "updated_at", label: "Updated", type: "date", sortable: true, filterable: false, defaultVisible: false },
    ],
  },
  {
    key: "activities",
    label: "Activity Log",
    table: "activities",
    description: "System-wide activity and audit trail",
    category: "System",
    defaultSort: "created_at",
    defaultSortDir: "desc",
    columns: [
      { key: "id", label: "ID", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "activity_type", label: "Activity Type", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "title", label: "Title", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "description", label: "Description", type: "text", sortable: false, filterable: true, defaultVisible: true },
      { key: "actor_name", label: "Actor", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "crew_id", label: "Crew ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "ship_id", label: "Ship ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "voyage_id", label: "Voyage ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "created_at", label: "When", type: "date", sortable: true, filterable: true, defaultVisible: true },
    ],
  },
  {
    key: "crew_checkins",
    label: "Crew Check-Ins",
    table: "crew_checkins",
    description: "Crew check-in records with location tracking",
    category: "Crew",
    defaultSort: "checked_at",
    defaultSortDir: "desc",
    columns: [
      { key: "id", label: "ID", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "crew_id", label: "Crew ID", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "voyage_id", label: "Voyage ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "ship_id", label: "Ship ID", type: "text", sortable: true, filterable: true, defaultVisible: false },
      { key: "check_type", label: "Check Type", type: "badge", sortable: true, filterable: true, defaultVisible: true },
      { key: "checked_at", label: "Checked At", type: "date", sortable: true, filterable: true, defaultVisible: true },
      { key: "location", label: "Location", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "recorded_by", label: "Recorded By", type: "text", sortable: true, filterable: true, defaultVisible: true },
      { key: "notes", label: "Notes", type: "text", sortable: false, filterable: false, defaultVisible: false },
      { key: "created_at", label: "Created", type: "date", sortable: true, filterable: false, defaultVisible: false },
    ],
  },
]

export function getDataSource(key: string): DataSourceDefinition | undefined {
  return DATA_SOURCES.find(s => s.key === key)
}

export function getDataSourceCategories(): string[] {
  return [...new Set(DATA_SOURCES.map(s => s.category))]
}
