// Permission registry - modular, expandable permission definitions
// Format: "category:action" (e.g. "ships:edit", "map:sources")
// Add new permissions here as features grow

export const PERMISSION_CATEGORIES = {
  DASHBOARD: 'dashboard',
  SHIPS: 'ships',
  CREW: 'crew',
  VOYAGES: 'voyages',
  CAMPAIGNS: 'campaigns',

  AVAILABILITY: 'availability',
  TASKS: 'tasks',
  TOOLS: 'tools',
  DOCUMENTS: 'documents',
  SETTINGS: 'settings',
  USERS: 'users',
  ROLES: 'roles',
  REPORTS: 'reports',
  UPLOAD: 'upload',
  HOWTO: 'howto',
  BILLING: 'billing',
  BACKUP: 'backup',
  CUSTOM_FIELDS: 'custom_fields',
  NOTIFICATIONS: 'notifications',
  IMPORT: 'import',
} as const

export const PERMISSION_ACTIONS = {
  VIEW: 'view',
  CREATE: 'create',
  EDIT: 'edit',
  DELETE: 'delete',
  USE: 'use',
  UPLOAD: 'upload',
  EXPORT: 'export',

} as const

// Define all permissions by category
export const PERMISSIONS = {
  DASHBOARD: {
    VIEW: `${PERMISSION_CATEGORIES.DASHBOARD}:${PERMISSION_ACTIONS.VIEW}`,
  },
  SHIPS: {
    VIEW: `${PERMISSION_CATEGORIES.SHIPS}:${PERMISSION_ACTIONS.VIEW}`,
    CREATE: `${PERMISSION_CATEGORIES.SHIPS}:${PERMISSION_ACTIONS.CREATE}`,
    EDIT: `${PERMISSION_CATEGORIES.SHIPS}:${PERMISSION_ACTIONS.EDIT}`,
    DELETE: `${PERMISSION_CATEGORIES.SHIPS}:${PERMISSION_ACTIONS.DELETE}`,
  },
  CREW: {
    VIEW: `${PERMISSION_CATEGORIES.CREW}:${PERMISSION_ACTIONS.VIEW}`,
    CREATE: `${PERMISSION_CATEGORIES.CREW}:${PERMISSION_ACTIONS.CREATE}`,
    EDIT: `${PERMISSION_CATEGORIES.CREW}:${PERMISSION_ACTIONS.EDIT}`,
    DELETE: `${PERMISSION_CATEGORIES.CREW}:${PERMISSION_ACTIONS.DELETE}`,
  },
  VOYAGES: {
    VIEW: `${PERMISSION_CATEGORIES.VOYAGES}:${PERMISSION_ACTIONS.VIEW}`,
    CREATE: `${PERMISSION_CATEGORIES.VOYAGES}:${PERMISSION_ACTIONS.CREATE}`,
    EDIT: `${PERMISSION_CATEGORIES.VOYAGES}:${PERMISSION_ACTIONS.EDIT}`,
    DELETE: `${PERMISSION_CATEGORIES.VOYAGES}:${PERMISSION_ACTIONS.DELETE}`,
  },
  CAMPAIGNS: {
    VIEW: `${PERMISSION_CATEGORIES.CAMPAIGNS}:${PERMISSION_ACTIONS.VIEW}`,
    CREATE: `${PERMISSION_CATEGORIES.CAMPAIGNS}:${PERMISSION_ACTIONS.CREATE}`,
    EDIT: `${PERMISSION_CATEGORIES.CAMPAIGNS}:${PERMISSION_ACTIONS.EDIT}`,
    DELETE: `${PERMISSION_CATEGORIES.CAMPAIGNS}:${PERMISSION_ACTIONS.DELETE}`,
  },

  AVAILABILITY: {
    VIEW: `${PERMISSION_CATEGORIES.AVAILABILITY}:${PERMISSION_ACTIONS.VIEW}`,
    EDIT: `${PERMISSION_CATEGORIES.AVAILABILITY}:${PERMISSION_ACTIONS.EDIT}`,
  },
  TASKS: {
    VIEW: `${PERMISSION_CATEGORIES.TASKS}:${PERMISSION_ACTIONS.VIEW}`,
    CREATE: `${PERMISSION_CATEGORIES.TASKS}:${PERMISSION_ACTIONS.CREATE}`,
    EDIT: `${PERMISSION_CATEGORIES.TASKS}:${PERMISSION_ACTIONS.EDIT}`,
    DELETE: `${PERMISSION_CATEGORIES.TASKS}:${PERMISSION_ACTIONS.DELETE}`,
  },
  TOOLS: {
    VIEW: `${PERMISSION_CATEGORIES.TOOLS}:${PERMISSION_ACTIONS.VIEW}`,
    USE: `${PERMISSION_CATEGORIES.TOOLS}:${PERMISSION_ACTIONS.USE}`,
  },
  DOCUMENTS: {
    VIEW: `${PERMISSION_CATEGORIES.DOCUMENTS}:${PERMISSION_ACTIONS.VIEW}`,
    UPLOAD: `${PERMISSION_CATEGORIES.DOCUMENTS}:${PERMISSION_ACTIONS.UPLOAD}`,
    DELETE: `${PERMISSION_CATEGORIES.DOCUMENTS}:${PERMISSION_ACTIONS.DELETE}`,
  },
  SETTINGS: {
    VIEW: `${PERMISSION_CATEGORIES.SETTINGS}:${PERMISSION_ACTIONS.VIEW}`,
    EDIT: `${PERMISSION_CATEGORIES.SETTINGS}:${PERMISSION_ACTIONS.EDIT}`,
  },
  USERS: {
    VIEW: `${PERMISSION_CATEGORIES.USERS}:${PERMISSION_ACTIONS.VIEW}`,
    CREATE: `${PERMISSION_CATEGORIES.USERS}:${PERMISSION_ACTIONS.CREATE}`,
    EDIT: `${PERMISSION_CATEGORIES.USERS}:${PERMISSION_ACTIONS.EDIT}`,
    DELETE: `${PERMISSION_CATEGORIES.USERS}:${PERMISSION_ACTIONS.DELETE}`,
  },
  ROLES: {
    VIEW: `${PERMISSION_CATEGORIES.ROLES}:${PERMISSION_ACTIONS.VIEW}`,
    CREATE: `${PERMISSION_CATEGORIES.ROLES}:${PERMISSION_ACTIONS.CREATE}`,
    EDIT: `${PERMISSION_CATEGORIES.ROLES}:${PERMISSION_ACTIONS.EDIT}`,
    DELETE: `${PERMISSION_CATEGORIES.ROLES}:${PERMISSION_ACTIONS.DELETE}`,
  },
  REPORTS: {
    VIEW: `${PERMISSION_CATEGORIES.REPORTS}:${PERMISSION_ACTIONS.VIEW}`,
    EXPORT: `${PERMISSION_CATEGORIES.REPORTS}:${PERMISSION_ACTIONS.EXPORT}`,
  },
  UPLOAD: {
    CSV: `${PERMISSION_CATEGORIES.UPLOAD}:csv`,
  },
  HOWTO: {
    VIEW: `${PERMISSION_CATEGORIES.HOWTO}:${PERMISSION_ACTIONS.VIEW}`,
  },
  BILLING: {
    VIEW: `${PERMISSION_CATEGORIES.BILLING}:${PERMISSION_ACTIONS.VIEW}`,
    CREATE: `${PERMISSION_CATEGORIES.BILLING}:${PERMISSION_ACTIONS.CREATE}`,
    EDIT: `${PERMISSION_CATEGORIES.BILLING}:${PERMISSION_ACTIONS.EDIT}`,
  },
  BACKUP: {
    VIEW: `${PERMISSION_CATEGORIES.BACKUP}:${PERMISSION_ACTIONS.VIEW}`,
    CREATE: `${PERMISSION_CATEGORIES.BACKUP}:${PERMISSION_ACTIONS.CREATE}`,
  },
  CUSTOM_FIELDS: {
    VIEW: `${PERMISSION_CATEGORIES.CUSTOM_FIELDS}:${PERMISSION_ACTIONS.VIEW}`,
    CREATE: `${PERMISSION_CATEGORIES.CUSTOM_FIELDS}:${PERMISSION_ACTIONS.CREATE}`,
    EDIT: `${PERMISSION_CATEGORIES.CUSTOM_FIELDS}:${PERMISSION_ACTIONS.EDIT}`,
    DELETE: `${PERMISSION_CATEGORIES.CUSTOM_FIELDS}:${PERMISSION_ACTIONS.DELETE}`,
  },
  NOTIFICATIONS: {
    VIEW: `${PERMISSION_CATEGORIES.NOTIFICATIONS}:${PERMISSION_ACTIONS.VIEW}`,
    CREATE: `${PERMISSION_CATEGORIES.NOTIFICATIONS}:${PERMISSION_ACTIONS.CREATE}`,
    EDIT: `${PERMISSION_CATEGORIES.NOTIFICATIONS}:${PERMISSION_ACTIONS.EDIT}`,
    DELETE: `${PERMISSION_CATEGORIES.NOTIFICATIONS}:${PERMISSION_ACTIONS.DELETE}`,
  },
  IMPORT: {
    VIEW: `${PERMISSION_CATEGORIES.IMPORT}:${PERMISSION_ACTIONS.VIEW}`,
    CREATE: `${PERMISSION_CATEGORIES.IMPORT}:${PERMISSION_ACTIONS.CREATE}`,
    DELETE: `${PERMISSION_CATEGORIES.IMPORT}:${PERMISSION_ACTIONS.DELETE}`,
  },
} as const

// Get all permission strings as a flat array for seeding
export function getAllPermissions(): string[] {
  const perms: string[] = []
  Object.values(PERMISSIONS).forEach(category => {
    Object.values(category).forEach(perm => {
      if (typeof perm === 'string' && !perms.includes(perm)) {
        perms.push(perm)
      }
    })
  })
  return perms
}

// Get permissions by category (useful for UI grouping)
export function getPermissionsByCategory(category: keyof typeof PERMISSION_CATEGORIES): string[] {
  const cat = PERMISSION_CATEGORIES[category]
  return getAllPermissions().filter(p => p.startsWith(cat))
}

// Check if a permission exists in the registry
export function isValidPermission(permission: string): boolean {
  return getAllPermissions().includes(permission)
}
